pipeline {
    agent any
    stages {
        stage('Example Build') {
            steps {
                echo 'Example Build'
                echo 'I\'m `hostname`'
                sh 'ifconfig'
            }
        }
        stage('Example Text') {
            steps {
                echo 'Example Test'
                echo 'I\'m `hostname`'
                sh 'java -version'
            }
        }
    }
}